name: desktop-stack

networks:
  proxy:
    external: true
    name: proxy

services:
  desktop:
    container_name: linux-desktop
    image: accetto/ubuntu-vnc-xfce-g3:latest
    restart: always
    shm_size: "1gb"
    environment:
      - VNC_PW=${DESKTOP_VNC_PASSWORD}
      - VNC_RESOLUTION=1280x720
    networks:
      - proxy
    volumes:
      - ${DESKTOP_APP_DATASET_CONFIG}:/home/headless
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.webtop.rule=Host(`desktop.vr-worlds.eu`)
      - traefik.http.routers.webtop.entrypoints=web
      # 🎯 noVNC listens on HTTP port 6901:
      - traefik.http.services.webtop.loadbalancer.server.port=6901

      # 🔒 Microsoft Entra ID Protection
      - traefik.http.routers.webtop.middlewares=entra-auth@docker